apps/first_app/urls.py
from django.conf.urls import url
from . import views
from views import *          # So we can call functions from our routes!
urlpatterns = [
    url(r'^$', index, name = "index"),
    url(r'^display$', display, name = "display"),          
    url(r'^process_registration$', process_registration, name = 'process_registration'),
    url(r'^process_login$', process_login, name = 'process_login'),
    url(r'^get_weather$', get_weather, name = 'get_weather'),
    url(r'^get_friend_weather$', get_friend_weather, name = 'get_friend_weather'),
    url(r'^process_friend/(?P<id>[^\n]+)/$', process_friend, name = 'process_friend'),
    url(r'^login$', login, name = 'login'),
    url(r'^log_out$', log_out, name = 'log_out'), 
]

weather_mood_booster/urls.py
from django.conf.urls import url, include # Notice we added include
from django.contrib import admin
urlpatterns = [
	url(r'^', include('apps.first_app.urls', namespace='first_app')), 
]

apps/first_app/models.py
from __future__ import unicode_literals
from django.contrib import messages
import re
import datetime
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^[A-Za-z_-]*$')

# validations
class UserManager(models.Manager):
      def login(self, postData, sessionData, request):
            error = False
            email = postData['email']
            password = postData['psw']
            try:
                  user = User.objects.get(email=email)
                  encrypted_password = bcrypt.hashpw(str(password).encode(), str(user.salt).encode())
                  if user.password == encrypted_password:
                        sessionData['logged_in'] = email
                        # print sessionData['logged_in']
                        error = False
                  else:
                        messages.error(request, 'Invalid Password!')
                        error = True
                        sessionData['logged_in'] = False
            except:
                  messages.error(request, 'Invalid Email Address!')
                  error = True 
                  sessionData['logged_in'] = False 
            if error:
                  return False
            else: 
                  return True
          
      # for now i am passing in the entire request object for the sake of the django messages, and i am using session to repopulate the fields
      def register(self, postData, sessionData, request):
            error = False
            sessionData['first_name'] = postData['first_name']
            sessionData['last_name'] = postData['last_name']
            sessionData['email'] = postData['email'] 
            password = postData['psw']
            password_rpt = postData['psw-repeat']
            if len(sessionData['email']) < 1:
                  messages.error(request, 'Email cannot be blank!')
                  error = True
            if len(password) < 9:
                  messages.error(request, 'Password must be at least 8 charachters!')
                  error = True
            if password != password_rpt:
                  messages.error(request, 'Password does not match!')        
                  error = True
            if len(sessionData['first_name']) < 2:
                  messages.error(request, 'Name must have at least 2 letters!') 
                  error = True
            if len(sessionData['last_name']) < 2:
                  messages.error(request, 'Name must have at least 2 letters!')  
                  error = True
            if not NAME_REGEX.match(sessionData['first_name']):
                  messages.error(request, 'Only letters please!')
                  error = True
            if not NAME_REGEX.match(sessionData['last_name']):
                  messages.error(request, 'Only letters please!')
                  error = True
            if not EMAIL_REGEX.match(sessionData['email']):
                  messages.error(request, 'Invalid Email Address!')
                  error = True
            else:
                  if User.objects.filter(email=sessionData['email']).exists():
                        email_exists =  True
                        error = True
                        messages.error(request, 'Email address not available, choose a different one, or click login to go to login') 
                  else:
                        email_exists = False
                        messages.success(request, 'Success!')
                        error = False
                        salt =  bcrypt.gensalt()
                        hashed_pw = bcrypt.hashpw(str(password).encode(), str(salt).encode())
                        User.objects.create(first_name = sessionData['first_name'], last_name= sessionData['last_name'], email = sessionData['email'],  password=hashed_pw, salt = salt)
                        sessionData['logged_in'] = sessionData['email']
                        sessionData.pop('first_name')
                        sessionData.pop('last_name')
                        sessionData.pop('email')
                        
            if error:
                  return False
            else: 
                  return True

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    salt = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()
    def __str__(self):
        return self.first_name + " " + self.last_name

class Friend(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    latitude = models.FloatField()
    longitude = models.FloatField()
    user = models.ForeignKey(User, related_name="friends") 
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.first_name + " " + self.last_name

apps/first_app/views.py
from django.shortcuts import render, HttpResponse, redirect
import requests
import json
import schedule
import time
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.urlresolvers import reverse
import re
import datetime
import pytz
from .models import User, Friend

# Create your views here.


def get_quotes(request):
    categories = ["inspire", "management", "life", "funny", "love"]
    for category in categories:
        url = 'http://quotes.rest/qod.json?category=' + category
        r = requests.get(url, headers={
          "Accept": "application/json", 
          "X-TheySaidSo-Api-Secret": "gR1fznrpGzxYK6MIyrOZjQeF"})
        print "api called"
        quote = r.json()
        # print quote['contents']['quotes'][0]['quote']
        if category not in request.session.keys():
            request.session[category] = quote
            print request.session[category]
        else:
            request.session[category] = quote
            print request.session[category]


def get_weather(request):
    if request.method == "POST" and request.is_ajax():
        print "reached getweather"
        lat = request.POST['lat']
        lon = request.POST['lon']
        url = "http://api.openweathermap.org/data/2.5/weather?lat=" + \
            lat + "&lon=" + lon + "&APPID=91d2fecd81cd087af9adf3d373fd0276"
        r = requests.get(url)
        print "api called"
        weather = r.json()
        kelvin = weather['main']['temp']
        print kelvin
        conditions = weather['weather'][0]['main']
        print conditions
        print request.session['funny']
        if 'weather' not in request.session.keys():
            request.session['weather'] = weather
            print request.session['weather']
        else:
            request.session['weather'] = weather
        context = {
                'funny': request.session['funny'],
                'life': request.session['life'],
                'management': request.session['management'],
                'inspire': request.session['inspire'],
                'city': request.session['weather']['name'],
                'fahrenheit': int(round((kelvin*9/5.0)-459.67)),
                'celcius': int(round(kelvin-273.15)),
                'conditions': conditions,
            }

        # print weather['name']
        
        return render(request, "first_app/weather.html", context)

def get_friend_weather(request):
    current_user = User.objects.get(email=request.session['logged_in'])
    count = 0
    friends_list = []
    friends = Friend.objects.filter(user = current_user)
    print "reached getweather"
    for friend in friends:
        lat = str(friend.latitude)
        lon = str(friend.longitude)
        url = "http://api.openweathermap.org/data/2.5/weather?lat=" + \
        lat + "&lon=" + lon + "&APPID=91d2fecd81cd087af9adf3d373fd0276"
        r = requests.get(url)
        print "api called"
        weather = r.json()
        kelvin = weather['main']['temp']
        print kelvin
        conditions = weather['weather'][0]['main']
        print conditions
        conditions = weather['weather'][0]['main']
        friend_dict = {
        'friend': friend,
        'weather': weather,
        'fahrenheit': int(round((kelvin*9/5.0)-459.67)),
        'conditions':conditions  
        }
        friends_list.append(friend_dict)

    print friends_list

    context = {
    'friends_list': friends_list,
    }
    return render(request, "first_app/friends_weather.html", context)
            


def process_friend(request, id):
    if request.method == "POST":
        print "reached process_friend"
        user = User.objects.get(id=id)
        new_friend= Friend.objects.create(first_name = request.POST['first_name'], last_name = request.POST['last_name'], latitude = request.POST['latitude'],  longitude = request.POST['longitude'], user = user)
        print new_friend
    return redirect('/')


def index(request):
    if 'logged_in' not in request.session.keys():
        request.session['logged_in'] = False
        print request.session['logged_in']
        return render(request, "first_app/register.html")
    if request.session['logged_in'] == False:
        return render(request, "first_app/register.html")
        print request.session['logged_in']
    else:
        print request.session['logged_in']
        return redirect('/display')


def process_registration(request):
    if request.method == "POST":
        error = False
        # for now i am passing in the entire request object for the sake of the django messages(will fix), and i am using session to repopulate the fields,
        user = User.objects.register(request.POST, request.session, request)
        error = False
        if user:
            get_quotes(request)
            return redirect('/display')
        return redirect('/')
    return redirect('/')


def process_login(request):
    if request.method == "POST":
        error = False
        # for now i am passing in the entire request object for the sake of the django messages(will fix), and i am using session to repopulate the fields
        user = User.objects.login(request.POST, request.session, request)
        if user:
            get_quotes(request)
            return redirect('/display')
        else:
            return redirect('/login')
        return redirect('/login')


def login(request):
    return render(request, "first_app/login.html")


def log_out(request):
    request.session.pop('logged_in')
    return redirect('/login')


def display(request):
    try:
        if request.session['logged_in'] == False:
            return redirect('/')
            print request.session['logged_in']
    except:
        request.session['logged_in'] == False

    else:
        current_user = User.objects.get(email=request.session['logged_in'])
        context = {
            "current_user": current_user,
        }
        return render(request, 'first_app/display.html', context)

apps/first_app/templates/first_app/add_friend.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>add friend</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
     <script src="https://maps.googleapis.com/maps/api/js?&libraries=places&callback=initAutocomplete"
         async defer></script>

    <style>
        /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
            height: 200px;
            width: 300px;
            margin: 0px;
            padding: 0px;
            border: 2px solid black;
            display: inline-block;
        }
      /* Optional: Makes the sample page fill the window. */
      #pac-input,.pac-card{background-color:#fff}body,html{height:100%;margin:0;padding:0}#description{font-family:Roboto;font-size:15px;font-weight:300}#infowindow-content .title{font-weight:700}#pac-input,.pac-controls label{font-family:Roboto;font-weight:300}#infowindow-content{display:none}#map #infowindow-content{display:inline}.pac-card{margin:10px 10px 0 0;border-radius:2px 0 0 2px;box-sizing:border-box;-moz-box-sizing:border-box;outline:0;box-shadow:0 2px 6px rgba(0,0,0,.3);font-family:Roboto}#pac-container{padding-bottom:12px;margin-right:12px}.pac-controls{display:inline-block;padding:5px 11px}.pac-controls label{font-size:13px}#pac-input{font-size:15px;margin-left:12px;padding:0 11px 0 13px;text-overflow:ellipsis;width:50%}#pac-input:focus{border-color:#4d90fe}#title{color:#fff;background-color:#4d90fe;font-size:25px;font-weight:500;padding:6px 12px}#target{width:345px}
    </style>
</head>

<body>
    <form action="{%url 'first_app:process_friend' id=current_user.id %}" method="POST">
        {% csrf_token %}
        <p>Add a friend</p>
        <label><b>First Name</b></label>
        <input type="text" placeholder="First Name" name="first_name" required><br>

        <label><b>Last Name</b></label>
        <input type="text" placeholder="Last Name" name="last_name" required><br>

        <input id="pac-input" class="controls" type="text" placeholder="Search Box">
   
        <div id="map"></div><br>
 

        <label><b>Location</b></label>
        <input id="location" type="text" placeholder="location" name="location" required><br>

        <label><b>latitude</b></label>
        <input id="lat" type="text" placeholder="latitude" name="latitude" required><br>

        <label><b>longitude</b></label>
        <input id="lng" type="text" placeholder="longitude" name="longitude" required><br>

        <button type="submit" >Add friend</button>
    </form>

   <script>
    function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 41.8500300, lng: -87.6500500},
          zoom: 13,
        });
        var geocoder = new google.maps.Geocoder();

        google.maps.event.addListener(map, 'click', function (event) {
            geocoder.geocode({
                'latLng': event.latLng
            }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        alert(results[0].formatted_address);
                        var lat = event.latLng.lat();
                        var lng = event.latLng.lng();
                        console.log(event.latLng);
                        console.log(lat);
                        $("#location").val(results[0].formatted_address);
                        $("#lat").val(lat);
                        $("#lng").val(lng);
                        console.log(lng);
                        alert(event.latLng);
                    }
                }
            });
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // // Create a marker for each place.
            // markers.push(new google.maps.Marker({
            //   map: map,
            //   icon: icon,
            //   title: place.name,
            //   position: place.geometry.location
            // }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
   
</body>

</html>

apps/first_app/templates/first_app/display.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Weather Mood Booster</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load static %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <script src="https://maps.googleapis.com/maps/api/js?&libraries=places&callback=initAutocomplete&key=AIzaSyA4EVPYRRI8TUuSu7P4wUlg3uv6Fe6HpRQ" async defer></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=59318da56d23c50012b5942d&product=inline-share-buttons"></script>

    <link rel="stylesheet" href="{% static 'first_app/css/style.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel='stylesheet' href="{% static 'first_app/css/styles.css' %}">
    <link rel='stylesheet' href="{% static 'first_app/css/tooltips.css' %}">
    <script src="{% static 'first_app/js/tooltips.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister|Barrio|Luckiest+Guy|BioRhyme|Black+Ops+One|Bungee|Bungee+Shade|Cabin|Creepster|Ewert|Fruktur|Gravitas+One|Inconsolata|Monoton|Nunito|Nunito+Sans|Pacifico|Quicksand|Rubik:400,900|VT323"
        rel="stylesheet">

</head>
<style>

</style>

<body>
    <div class="header box14">
        <h1> Hey there {{ current_user.first_name }}!</h1>
        <a href="/log_out">log off</a><br>
    </div>
    <br>


    <div id="loadingDiv">
        <div class="cssload-loader-inner">
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap"></div>
            </div>
            <div class="cssload-cssload-loader-line-wrap-wrap">
                <div class="cssload-loader-line-wrap"></div>
            </div>
        </div>
    </div>

    <div id="display_content"></div><br>
    <!--<button id="friend_weather_btn" type="button" class="btn btn-primary btn-lg VT323" data-toggle="modal" data-target="#friends_weather">View Friends Weather</button>
    <button id="add_friend_btn" type="button" class="btn btn-primary btn-lg VT323" data-toggle="modal" data-target="#myModal">Add Friend</button>-->
    <div id="buttons">
        <ul>
            <li><a href="#" class="round yellow">Add Friend<span class="round" data-toggle="modal" data-target="#myModal">Click here to add friends</span></a></li>
            <li><a href="#" class="round red">Friends<span class="round" data-toggle="modal" data-target="#friends_weather">Are you sure? This might negatively affect your mood</span></a></li>
        </ul>
    </div>
    

    <!-- Modal -->
    <div class="modal fade" id="friends_weather" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h2 class="modal-title" id="myModalLabel">"I'm too busy working on my own grass to notice if yours is greener"</h2>
                </div>
                <div class="modal-body">
                    <div id="display_friends_weather"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Button trigger modal -->

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add a Friend</h4>
                </div>
                <div class="modal-body">
                    <form action="{%url 'first_app:process_friend' id=current_user.id %}" method="POST">
                        {% csrf_token %}
                        <p>Add a friend</p>
                        <label><b>First Name</b></label>
                        <input type="text" placeholder="First Name" name="first_name" required><br>

                        <label><b>Last Name</b></label>
                        <input type="text" placeholder="Last Name" name="last_name" required><br>
                        <div class="col-md-12">
                            <input id="pac-input" class="controls" type="text" placeholder="Search Box">
                            <div id="map"></div><br>
                        </div>

                        <label><b>Location</b></label>
                        <input id="location" type="text" placeholder="location" name="location" required><br>

                        <label><b>latitude</b></label>
                        <input id="lat" type="text" placeholder="latitude" name="latitude" required><br>

                        <label><b>longitude</b></label>
                        <input id="lng" type="text" placeholder="longitude" name="longitude" required><br>

                        <button type="submit">Add friend</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div id="share_this" class="box14">

        <div  class="VT323">
            <h3>Does your friend need to see this quote?</h3>
            <div class="sharethis-inline-share-buttons"></div>
        </div>
    </div>
    <!-- Button trigger modal -->


    <script>
        function initAutocomplete() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: 41.8500300, lng: -87.6500500 },
                zoom: 13,
            });
            var geocoder = new google.maps.Geocoder();

            google.maps.event.addListener(map, 'click', function (event) {
                geocoder.geocode({
                    'latLng': event.latLng
                }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            // alert(results[0].formatted_address);
                            var lat = event.latLng.lat();
                            var lng = event.latLng.lng();
                            console.log(event.latLng);
                            console.log(lat);
                            $("#location").val(results[0].formatted_address);
                            $("#lat").val(lat);
                            $("#lng").val(lng);
                            console.log(lng);
                            // alert(event.latLng);
                        }
                    }
                });
            });

            // Create the search box and link it to the UI element.
            var input = document.getElementById('pac-input');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            // Bias the SearchBox results towards current map's viewport.
            map.addListener('bounds_changed', function () {
                searchBox.setBounds(map.getBounds());
            });

            var markers = [];
            // Listen for the event fired when the user selects a prediction and retrieve
            // more details for that place.
            searchBox.addListener('places_changed', function () {
                var places = searchBox.getPlaces();

                if (places.length == 0) {
                    return;
                }

                // Clear out the old markers.
                markers.forEach(function (marker) {
                    marker.setMap(null);
                });
                markers = [];

                // For each place, get the icon, name and location.
                var bounds = new google.maps.LatLngBounds();
                places.forEach(function (place) {
                    if (!place.geometry) {
                        console.log("Returned place contains no geometry");
                        return;
                    }
                    var icon = {
                        url: place.icon,
                        size: new google.maps.Size(71, 71),
                        origin: new google.maps.Point(0, 0),
                        anchor: new google.maps.Point(17, 34),
                        scaledSize: new google.maps.Size(25, 25)
                    };

                    // // Create a marker for each place.
                    // markers.push(new google.maps.Marker({
                    //   map: map,
                    //   icon: icon,
                    //   title: place.name,
                    //   position: place.geometry.location
                    // }));

                    if (place.geometry.viewport) {
                        // Only geocodes have viewport.
                        bounds.union(place.geometry.viewport);
                    } else {
                        bounds.extend(place.geometry.location);
                    }
                });
                map.fitBounds(bounds);
            });
            $('#myModal').on('shown.bs.modal', function () {
                google.maps.event.trigger(map, 'resize');

            });
        }
    </script>

    <script>
        $(document).ready(function () {
            if ("geolocation" in navigator) { //check geolocation available 
                //try to get user current location using getCurrentPosition() method
                navigator.geolocation.getCurrentPosition(function (position) {
                    var lat = position.coords.latitude;
                    var lon = position.coords.longitude;
                    console.log("Found your location \nLat : " + position.coords.latitude + " \nLang :" + position.coords.longitude);
                    // $.post("/get_weather", { lat: position.coords.latitude, lon: position.coords.longitude });
                    $.ajax({
                        url: "/get_weather",
                        type: "POST",
                        data: { lat: position.coords.latitude, lon: position.coords.longitude, csrfmiddlewaretoken: '{{ csrf_token }}' },
                        success: function (serverResponse) {
                            // Replace the html inside a div with the class "posts" with the server response
                            // console.log("Received this from server: ", serverResponse)
                            $('#display_content').html(serverResponse)
                        }
                    });
                    $.ajax({
                        url: "/get_friend_weather",
                        type: "POST",
                        data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
                        success: function (serverResponse) {
                            // Replace the html inside a div with the class "posts" with the server response
                            // console.log("Received this from server: ", serverResponse)
                            $('#display_friends_weather').html(serverResponse)
                        }
                    });
                });
            } else {
                console.log("Browser doesn't support geolocation!");
            }


        });
    </script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?&libraries=places&callback=initAutocomplete" async defer></script>-->


    <script>
        $(document).ajaxStart(function () {
            $("#loadingDiv").css("display", "block");

        });
        $(document).ajaxComplete(function () {
            $("#loadingDiv").css("display", "none");
            $("#display_content").addClass("display_content");
            $('#add_friend_btn').css("display", "inline-block");
            $('#share_this').css("display", "block");
            $('#buttons').css("display", "block");
            $('#friend_weather_btn').css("display", "inline-block");
            $("img[title]").tooltips();


        });
    </script>

</body>

</html>